DROP DATABASE IF EXISTS employe_bdd;
CREATE DATABASE employe_bdd;
USE employe_bdd;

CREATE TABLE DEPT
(DEPTNO TINYINT,
 DNAME VARCHAR (50),
 LOC VARCHAR (50) ,
 CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO)
 );

CREATE TABLE EMP
(EMPNO SMALLINT,
ENAME VARCHAR (50),
JOB VARCHAR (255),
MGR SMALLINT,
HIREDATE DATE,
SAL SMALLINT,
COMM SMALLINT,
DEPTNO TINYINT,
CONSTRAINT 	PK_EMPNO PRIMARY KEY (EMPNO)
);

ALTER TABLE EMP ADD CONSTRAINT fk_EMP_EMP FOREIGN KEY (MGR) REFERENCES EMP (EMPNO);

ALTER TABLE EMP ADD CONSTRAINT fk_EMP_DEPT FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO);
