DROP DATABASE IF EXISTS employe_bdd;
CREATE DATABASE employe_bdd;
USE employe_bdd;

CREATE TABLE DEPT(
DEPTNO SMALLINT PRIMARY KEY,
DNAME VARCHAR (50) NOT NULL,
LOC VARCHAR (50)  NOT NULL);

CREATE TABLE EMP (
EMPNO INT PRIMARY KEY,
ENAME VARCHAR (50) NOT NULL,
JOB VARCHAR (255) NOT NULL,
MGR INT,
HIREDATE DATE NOT NULL,
SAL DECIMAL (8,2) NOT nULL,
COMM DECIMAL (8,2),
DEPTNO SMALLINT NOT NULL
);


CREATE TABLE PROJETS (
NUMERO_DE_PROJET SMALLINT(3) AUTO_INCREMENT PRIMARY KEY,
NOM_DE_PROJET VARCHAR(5) NOT NULL,
BUDGET DECIMAL (15,2) NOT NULL
);

 

/*CREATE TABLE DEPT
(DEPTNO TINYINT,
 DNAME VARCHAR (50),
 LOC VARCHAR (50) ,
 CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO)
 );

CREATE TABLE EMP
(EMPNO SMALLINT,
ENAME VARCHAR (50),
JOB VARCHAR (255),
MGR SMALLINT,
HIREDATE DATE,
SAL SMALLINT,
COMM SMALLINT,
DEPTNO TINYINT,
CONSTRAINT 	PK_EMPNO PRIMARY KEY (EMPNO)
);

ALTER TABLE EMP ADD CONSTRAINT fk_EMP_EMP FOREIGN KEY (MGR) REFERENCES EMP (EMPNO);

ALTER TABLE EMP ADD CONSTRAINT fk_EMP_DEPT FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO);
*/
